ТЗ-13(1-ая итерация)
DTF98/java-shareit pull request #1
Opened 2024-05-25 12:11 UTC by DTF98

2024-05-25 16:41 UTC, TomattmanYandex reviewed
Привет, комментарии в пакете айтемов также относятся к таким же классам в пакете юзеров и наоборот, ибо мог что то пропустить

2024-05-25 16:41 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/ErrorHandler/ErrorHandler.java
> +package ru.practicum.shareit.ErrorHandler;
пакеты именуем с маленько буквы

2024-05-25 16:41 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    private final ItemService service;
я бы порекомендовал называть сервисы полными именами , потому что может появится еще один сервис и тогда прийдется либо менять имя предыдущего, либо будут имена в разном стиле

2024-05-25 16:41 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/mapper/ItemMapper.java
> +    public static ItemDto toItemDto(Item item) {
тоже просто на раздумия момент, можно такие метод называть короче, например просто toDto потому что из какого в какое понятно по имени класса

2024-05-25 16:41 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/service/impl/ItemServiceImpl.java
> +            userStorage.getById(userId);
я бы рекомендовал другой более лаконичный вариант реализации проверки на найденность
1) сделать так чтобы репозиторий возвращал не сам обьект, а optional с этим обьектом
2) получать optional и использовать конструкцию orElseThrow(exception)

таким образом избегается дополнительная вложенность и дополнительные ошибки, и очень удобно когда надо проверить несколько объектов

Еще вариант как можно сделать еще лучше
сделать приватный метод типа 
private User getUserById(Long id) {
return userRepository.findById(id).orElseThrow(exception);
}
таким образом вызов этого метода проверяет наличие обьекта и возвращает его, а если надо просто проверить, без требования самого значения, то можно не записывать результат выполнения в переменную

2024-05-25 16:41 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/service/impl/ItemServiceImpl.java
> +            List<Item> items = itemStorage.getAllByOwner(userId);
странная логика, получаем по овнеру, потом снова проверяем овенера в строчке 67
потом снова получаем уже только один элемент

1) проверить что пользователь существует
2) получить итем по id (тоже с проверкой что существует, реализовать как с пользователем)
3) проверить что пользователь овнер
4) обновить

2024-05-25 16:41 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/service/impl/ItemServiceImpl.java
> +            if (items.size() == 1) itemDto.setId(items.get(0).getId());
пожалуйста , даже если одна команда в блоке кода, используй фигурные скобки, без них код читается тяжело

2024-05-25 16:41 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/storage/ItemStorage.java
> +    public Item getById(Long id) {
уже писал, лучше чтобы метод возвращал optional
используй просто optional.ofNullable

2024-05-25 16:41 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/storage/ItemStorage.java
> +    public List<Item> searchItemsByNameAndDescription(String text) {
почему метод ищет по имени ИЛИ описанию, а имя по имени И описанию?

2024-05-25 16:41 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/user/service/impl/UserServiceImpl.java
> +        return storage.getAll().stream()
лучше в маппере перегрузить метод toUserDto чтобы принимал список и возвращал список, так вся логика маппинга будет в одном месте

2024-05-25 16:41 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/user/storage/UserEmailStorage.java
> +public class UserEmailStorage {
зачем тебе два хранилища? получается дублирование данных
для проверки наличия email просто ищешь в хранилище юзеров, юзера по email и если что то найдено, то email занят

2024-05-25 16:41 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/util/ErrorResponse.java
> +package ru.practicum.shareit.util;
я бы запихнул dto ошибки к обработчику ошибок

2024-05-26 04:19 UTC, DTF98 commented on src/main/java/ru/practicum/shareit/item/service/impl/ItemServiceImpl.java
> +            List<Item> items = itemStorage.getAllByOwner(userId);
Да, я сам не в восторге от этого участка кода, но, к сожалению, есть тест в постмане, который при обновлении не передает id item'а и пришлось доделывать логику так, что если у пользователя одна вещь в хозяйстве, так скажем, то ему не нужно передавать айдишник... Лишь только те поля которые он хочет изменить

2024-05-26 04:28 UTC, DTF98 commented on src/main/java/ru/practicum/shareit/user/storage/UserEmailStorage.java
> +public class UserEmailStorage {
Ну, я просто размышлял так: допустим представим микросервис, который отвечает за регистрацию пользователей, при попытке нового пользователя вводить почту ему же очень быстро показывается что такая почта уже существует(причем это делается динамически на некоторых сайтах, я имею ввиду, что человек даже кнопку "регистрация" не нажимает) я предположил, что данные либо хэшируются(по мере частоты использования ввода этой почты при авторизации допустим), либо у них есть какое-то свое хранилище откуда можно очень быстро такую уникальную вещь как почта или логин достать... Это мой вид такой реализации))) Я исправлю, конечно, просто хотел сказать, что я хотел реализовать(хоть и криво)

2024-05-27 08:22 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/service/impl/ItemServiceImpl.java
> +        userStorage.getById(userId);
1) это не выполнит проверку по существование, просто вернется Optional.empty
2) кажется надо сделать проверку например на овнера, иначе зачем это?

2024-05-27 08:22 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/service/impl/ItemServiceImpl.java
> +        userStorage.getById(userId).orElseThrow(() ->
коммент относится к тому, что ниже
я бы предложил вынести это 
userStorage.getById(userId).orElseThrow(() ->
                new NotFoundException(String.format("Не найден пользователь по id = %s", userId)));
        
в отдельный метод 
private User getUserById(Long id) {
  return userStorage.getById(userId).orElseThrow(() ->
                new NotFoundException(String.format("Не найден пользователь по id = %s", userId)));
}

так вызовом этого метода ты будешь проверять наличие пользователя в базе, и сможешь переиспользовать это

2024-05-27 08:22 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/service/impl/ItemServiceImpl.java
> +        /*
не надо таких проверок делать, у нас есть стандартное поведение, при обновлении пользователь передает идентификатор того, что хочет обновить, Если он ничего не передал, то мы кидаем ошибку

такое улучшение конечно может быть удобным, но слишком усложняет логику и все равно скорее всего никто такое использовать не будет

2024-05-27 08:22 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/service/impl/ItemServiceImpl.java
> +            List<Item> items = itemStorage.getAllByOwner(userId);
хммм, какие отстойные тесты в постмане, ладно, тогда оставляй так, но этот процесс не самый лучший с точки зрения архитектуры

2024-05-27 08:26 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/user/controller/UserController.java
> +    private final UserService service;
я же писал что тут такие же окментарии как и в пакете с item 
лучше дать полное имя переменной

2024-05-27 08:26 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/user/storage/UserEmailStorage.java
> +public class UserEmailStorage {
нет, обычно это запрос туда же, в соновное хранилище, и мы проверяем что пользователя с таким email не существует

2024-05-27 08:29 UTC, TomattmanYandex requested changes
я добавил еще парочку комментариев

2024-05-27 08:29 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/user/service/impl/UserServiceImpl.java
> +    private final UserStorage storage;
тут аналогично, лучше назвать userStorage

2024-05-27 08:29 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/user/service/impl/UserServiceImpl.java
> +        getById(userId);
я бы рекомендоватл сделать приватный метод, который будет возвращать с проверкой,  и возвращать именно User а не Dto потому что с User мы можем легко работать дальше

главная проблема будет в том, как разделить по именам эти методы)

2024-05-28 19:34 UTC, DTF98 commented on src/main/java/ru/practicum/shareit/user/service/impl/UserServiceImpl.java
> +        getById(userId);
У меня так не получится, у меня вся валидация на пустые поля по email завязана на user, а не на userDto, поэтому при частичном обновлении опять же допустим имени с пустым переданным email будет вылезать ошибка, если я буду собирать user'a поэтому я с DTO в апдейт работаю.

2024-05-29 07:53 UTC, TomattmanYandex approved these changes
Принято

2024-06-03 23:13 UTC, merged