Add bookings
DTF98/java-shareit pull request #3
Opened 2024-06-24 20:58 UTC by DTF98

2024-06-25 10:04 UTC, TomattmanYandex requested changes
Много однотипных проблем, я не помечал везде, но исправить стоит везде

2024-06-25 10:04 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/dto/AdvancedBookingDto.java
> +    Long id;
модификаторы доступа

2024-06-25 10:04 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +    Long id;
модификаторы доступа

2024-06-25 10:04 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDtoIn.java
> +    Long id;
модификаторы доступа

2024-06-25 10:04 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDtoIn.java
> +public class BookingDtoIn {
не очень понятные имена Dto и для чего они
Стоит назвать как то более полно

2024-06-25 10:04 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/model/BookingState.java
> +            bookingState = BookingState.ALL;
лучше было реализовать это дефолтным значением в параметре контроллера, а не таким образом

2024-06-25 10:04 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +                                                     @RequestParam(required = false) String state) {
state можно принимать сразу типа BookingState

2024-06-25 10:04 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/repository/AdvancedBookingRepository.java
> +public interface AdvancedBookingRepository {
Зачем нужны два интерфейса репозитория под одну сущность

2024-06-25 10:04 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/repository/impl/AdvancedBookingRepositoryImpl.java
> +        String sql = "SELECT DISTINCT ON (item_id) bk.* " +
1) такой запрос кажется можно создать именем метода
2) на метод в репозитории можно повесить аннотацию @NativeQuery и поместить там запрос с параметрами, чтобы не приходилось делать имплементацию метода

2024-06-25 10:04 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/dto/AdvancedItemDto.java
> +    Long id;
Модификаторы доступа

2024-06-25 10:04 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepository.java
> +    <T> Optional<T> findById(Long itemId, Class<T> type);
1) почему методы параметризированы дженериком, весь интерфейс уже параметризирован Item
2) этот метод есть автоматически, когда наследуешь интерйес от JpaRepository (разве  что без класса но он и не нужен, потмоу что все уже параметризированно)

2024-06-25 10:04 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/user/repository/UserRepository.java
> +    <T> Optional<T> findById(Long userId, Class<T> type);
то же что и в айтемах

2024-06-25 10:15 UTC, DTF98 commented on src/main/java/ru/practicum/shareit/booking/dto/AdvancedBookingDto.java
> +    Long id;
Я же использую аннотацию @Value, она устанавливает сама модификатор доступа
<img width="733" alt="Снимок экрана 2024-06-25 в 15 14 02" src="https://github.com/DTF98/java-shareit/assets/147542021/1068995c-25e3-4b2d-abf1-17e8977b2971">

2024-06-25 10:15 UTC, DTF98 commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +    Long id;
аннотация @Value

2024-06-25 10:15 UTC, DTF98 commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDtoIn.java
> +    Long id;
аннотация @Value

2024-06-25 10:48 UTC, DTF98 commented on src/main/java/ru/practicum/shareit/booking/model/BookingState.java
> +            bookingState = BookingState.ALL;
Да, я полностью согласен с этим, но к сожалению в тестах постмана есть такой тест "Booking get all for user 1 by wrong state" который ожидает увидеть конкретный ответ:
<img width="782" alt="Снимок экрана 2024-06-25 в 15 44 48" src="https://github.com/DTF98/java-shareit/assets/147542021/5af47225-7e26-47bc-926e-883f33981cc0">
Ошибку парсинга я конечно могу поймать в ErrorHandler, но никак не достану из лога или стек трейса ошибки само это название, которое тест ожидает увидеть... Ну если только не писать еще более ярко выраженный костыль, что если вылетает ошибка парсинга этого класа то всегда один и тот же ответ отправлять, это пройдет тесты, но будет намного хуже, мне кажется, других вариантов я на данный момент не вижу, если вы подскажите, буду премного благодарен)

2024-06-25 11:32 UTC, DTF98 commented on src/main/java/ru/practicum/shareit/item/dto/AdvancedItemDto.java
> +    Long id;
аннотация @value

2024-06-26 09:30 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/model/BookingState.java
> +            bookingState = BookingState.ALL;
да, это был комментарийтак, для напоминания, про этот тест я знаю

2024-06-26 09:31 UTC, TomattmanYandex approved these changes
Принято

2024-06-26 09:34 UTC, merged